
#############################RESTOURANT#################################################################################

###UserRestaurantRestController

# curl http://localhost:8080/mvs/rest/user/restaurants
GET http://localhost:8080/mvs/rest/user/restaurants

<> 2020-05-28T064932.400.html

###

# curl http://localhost:8080/mvs/rest/user/restaurants/100002
GET http://localhost:8080/mvs/rest/user/restaurants/100002

<> 2020-05-28T065318.200.json
<> 2020-05-28T065243.500.html

###

# curl http://localhost:8080/mvs/rest/user/restaurants/100003
GET http://localhost:8080/mvs/rest/user/restaurants/100003

###

# curl http://localhost:8080/mvs/rest/user/restaurants/by?name=McDonalds
GET http://localhost:8080/mvs/rest/user/restaurants/by?name=McDonalds

<> 2020-05-28T065734.200.json

###

# curl http://localhost:8080/mvs/rest/user/restaurants/by?name=Pizza_Hut
GET http://localhost:8080/mvs/rest/user/restaurants/by?name=Pizza_Hut

<> 2020-05-28T065827.200.json

###

###AdminRestaurantRestController

# curl http://localhost:8080/mvs/rest/admin/restaurants
GET http://localhost:8080/mvs/rest/admin/restaurants

<> 2020-05-28T070208.200.json

###

# curl http://localhost:8080/mvs/rest/admin/restaurants/100003
GET http://localhost:8080/mvs/rest/admin/restaurants/100003

<> 2020-05-28T070540.200.json
<> 2020-05-28T070531.200.json

###

# curl http://localhost:8080/mvs/rest/admin/restaurants/by?name=McDonalds
GET http://localhost:8080/mvs/rest/admin/restaurants/by?name=McDonalds

<> 2020-05-28T070757.200.json

###

### Create restaurant
# curl -X POST -d '{"name":"Mama_Roma","type":"Italian","address":"пр.Стачек","phone":"318-56-98","url":"mamaroma.ru"}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/restaurants
POST http://localhost:8080/mvs/rest/admin/restaurants
Content-Type: application/json

{
  "name": "Mama_Roma",
  "type": "Italian",
  "address": "пр.Стачек",
  "phone": "318-56-98",
  "url": "mamaroma.ru"
}

<> 2020-05-28T072526.201.json

###

# curl http://localhost:8080/mvs/rest/admin/restaurants/by?name=Mama_Roma
GET http://localhost:8080/mvs/rest/admin/restaurants/by?name=Mama_Roma

<> 2020-05-28T072743.200.json

###

# curl -X PUT -d '{"name":"Update_Roma","type":"UpdateItalian","address":"пр.СтачекUpdate","phone":"(812)318-56-98","url":"update.ru"}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/restaurants/100015
PUT http://localhost:8080/mvs/rest/admin/restaurants/100015
Content-Type: application/json

{
  "name": "Update_Roma",
  "type": "UpdateItalian",
  "address": "пр.СтачекUpdate",
  "phone": "(812)318-56-98",
  "url": "update.ru"
}


###
# curl http://localhost:8080/mvs/rest/admin/restaurants
GET http://localhost:8080/mvs/rest/admin/restaurants

<> 2020-05-28T074156.200.json

###

# DELETE restaurant id=100015
# curl -X DELETE http://localhost:8080/mvs/rest/admin/restaurants/100015
DELETE http://localhost:8080/mvs/rest/admin/restaurants/100015

###

# curl http://localhost:8080/mvs/rest/admin/restaurants
GET http://localhost:8080/mvs/rest/admin/restaurants

<> 2020-05-28T074609.200.json
###

################################USER####################################################################################

###AdminUserRestController

###getAll
# curl http://localhost:8080/mvs/rest/admin/users
GET http://localhost:8080/mvs/rest/admin/users

<> 2020-05-28T075757.200.json

### GET user id=100000
# curl http://localhost:8080/mvs/rest/admin/users/100000
GET http://localhost:8080/mvs/rest/admin/users/100000

<> 2020-05-28T081451.200.json

###

### Create user
# curl -X POST -d '{"name":"NewName","email":"new@nuevo.ru","password":"passwordNew","roles":["ROLE_USER"]}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/users
POST http://localhost:8080/mvs/rest/admin/users
Content-Type: application/json

{
  "name": "NewName",
  "email": "new@nuevo.ru",
  "password": "passwordNew",
  "roles": [
    "ROLE_USER"
  ]
}

<> 2020-05-28T082130.201.json

###update user 100016

# curl -X PUT -d '{"name":"NameUpdate","email":"update@gmail.com","password":"passwordUpdate"}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/users/100016
PUT http://localhost:8080/mvs/rest/admin/users/100016
Content-Type: application/json

{
  "name": "NameUpdate",
  "email": "update@gmail.com",
  "password": "passwordUpdate"
}

###

# curl http://localhost:8080/mvs/rest/admin/users
GET http://localhost:8080/mvs/rest/admin/users

<> 2020-05-28T082949.200.json

###

### DELETE user id=100016

# curl -X DELETE http://localhost:8080/mvs/rest/admin/users/100016
DELETE http://localhost:8080/mvs/rest/admin/users/100016

###

# curl http://localhost:8080/mvs/rest/admin/users
GET http://localhost:8080/mvs/rest/admin/users

<> 2020-05-28T084044.200.json
<> 2020-05-28T083317.200.json

###
# curl http://localhost:8080/mvs/rest/admin/users/by?email=user@yandex.ru
GET http://localhost:8080/mvs/rest/admin/users/by?email=user@yandex.ru

<> 2020-05-28T084115.200.json
<> 2020-05-28T083910.400.html


###

# curl -X PATCH -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/users/100000?enabled=false
PATCH http://localhost:8080/mvs/rest/admin/users/100000?enabled=false
Content-Type: application/json

### check enabled
# curl http://localhost:8080/mvs/rest/admin/users/by?email=user@yandex.ru
GET http://localhost:8080/mvs/rest/admin/users/by?email=user@yandex.ru

###

###ProfileUserRestController

### get user profile
# curl http://localhost:8080/mvs/rest/profile
GET http://localhost:8080/mvs/rest/profile

<> 2020-05-28T084647.200.json

### update user profile
# curl -X PUT -d '{"name":"NameUpdate","email":"update@gmail.com","password":"passwordUpdate"}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/profile
PUT http://localhost:8080/mvs/rest/profile
Content-Type: application/json

{
  "name": "NameUpdate",
  "email": "update@gmail.com",
  "password": "passwordUpdate"
}

### check
# curl http://localhost:8080/mvs/rest/profile
GET http://localhost:8080/mvs/rest/profile

<> 2020-05-28T085136.200.json

### delete user profile
# curl -X DELETE http://localhost:8080/mvs/rest/profile
DELETE http://localhost:8080/mvs/rest/profile

### check
# curl http://localhost:8080/mvs/rest/admin/users
GET http://localhost:8080/mvs/rest/admin/users

<> 2020-05-28T085943.200.json

################################DISH####################################################################################
###AdminDishRestController

###getAll With Restaurant
# curl http://localhost:8080/mvs/rest/admin/dishes
GET http://localhost:8080/mvs/rest/admin/dishes

<> 2020-05-28T090459.200.json

###
###get dish 100004
# curl http://localhost:8080/mvs/rest/admin/dishes/100004
GET http://localhost:8080/mvs/rest/admin/dishes/100004

<> 2020-05-28T090859.200.json


###create newDish by restaurantId 100002 with Restaurant on date
# curl -X POST -d '{"name":"FirstName","date":"2020-05-28","price":5000}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/dishes/100002
POST http://localhost:8080/mvs/rest/admin/dishes/100002
Content-Type: application/json

{
  "name": "FirstName",
  "date": "2020-05-28",
  "price": 5000
}

<> 2020-05-28T102031.201.json

###create newDish by restaurantId 100002 with Restaurant now

# curl -X POST -d '{"name":"SecondName","price":500}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/dishes/100002
POST http://localhost:8080/mvs/rest/admin/dishes/100002
Content-Type: application/json

{
  "name": "SecondName",
  "price": 500
}

<> 2020-05-28T102214.201.json

###

<> 2020-05-28T093846.201.json

###update Dish 100015 by restaurantId 100002
# curl -X PUT -d '{"id":100015,"name":"UpdateName","date":"2020-05-28","price":500}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/dishes/100002
PUT http://localhost:8080/mvs/rest/admin/dishes/100002
Content-Type: application/json

{
  "id": 100015,
  "name": "UpdateName",
  "date": "2020-05-28",
  "price": 500
}

###check
# curl http://localhost:8080/mvs/rest/admin/dishes
GET http://localhost:8080/mvs/rest/admin/dishes

<> 2020-05-28T102916.200.json

###getTodayMenu
# curl http://localhost:8080/mvs/rest/admin/dishes/by?restaurantId=100002
GET http://localhost:8080/mvs/rest/admin/dishes/by?restaurantId=100002

<> 2020-05-28T103215.200.json

### delete dish 100015
# curl -X DELETE http://localhost:8080/mvs/rest/admin/dishes/100015
DELETE http://localhost:8080/mvs/rest/admin/dishes/100015

### check
# curl http://localhost:8080/mvs/rest/admin/dishes/by?restaurantId=100002
GET http://localhost:8080/mvs/rest/admin/dishes/by?restaurantId=100002

<> 2020-05-28T103550.200.json

###
###getDayMenu
# curl http://localhost:8080/mvs/rest/admin/dishes/100002/by?date=2020-05-28
GET http://localhost:8080/mvs/rest/admin/dishes/100002/by?date=2020-05-30

<> 2020-05-28T104653.200.json
<> 2020-05-28T104638.200.json

###UserDishRestController
###getDayMenu
# curl http://localhost:8080/mvs/rest/user/dishes/100002/by?date=2020-05-28
GET http://localhost:8080/mvs/rest/user/dishes/100002/by?date=2020-05-28

<> 2020-05-28T114726.200.json

###

###getTodayMenu
# curl http://localhost:8080/mvs/rest/user/dishes/by?restaurantId=100002
GET http://localhost:8080/mvs/rest/user/dishes/by?restaurantId=100002

<> 2020-05-28T114815.200.json

###getAll With Restaurant
# curl http://localhost:8080/mvs/rest/user/dishes
GET http://localhost:8080/mvs/rest/user/dishes

<> 2020-05-28T114907.200.json

################################VOTE####################################################################################

###UserVoteRestController

###getWithRestaurant
# curl http://localhost:8080/mvs/rest/user/votes/100012
GET http://localhost:8080/mvs/rest/user/votes/100014

###



###getAllWithRestaurant
# curl http://localhost:8080/mvs/rest/user/votes
GET http://localhost:8080/mvs/rest/user/votes

<> 2020-05-28T115340.200.json

###getAllWithRestaurantByUserIdBetween
# curl http://localhost:8080/mvs/rest/user/votes/filter?startDate=2020-04-28&endDate=2020-05-31
GET http://localhost:8080/mvs/rest/user/votes/filter?startDate=2020-04-29&endDate=2020-04-29

<> 2020-05-28T115902.200.json



###create vote for 100002 (only LocalDate.now before 11-00)
# curl -X POST -H "Content-Type:application/json" http://localhost:8080/mvs/rest/user/votes/100002
POST http://localhost:8080/mvs/rest/user/votes/100002
Content-Type: application/json

###

###check
# curl http://localhost:8080/mvs/rest/user/votes
GET http://localhost:8080/mvs/rest/user/votes

<> 2020-05-29T124554.200.json

###

###update  vote (vote in favor of another one) for 100003 (only LocalDate.now before 11-00)
# curl -X POST -H "Content-Type:application/json" http://localhost:8080/mvs/rest/user/votes/100003
POST http://localhost:8080/mvs/rest/user/votes/100003
Content-Type: application/json

###
###check
# curl http://localhost:8080/mvs/rest/user/votes
GET http://localhost:8080/mvs/rest/user/votes

<> 2020-05-29T124624.200.json

###
###delete vote (only LocalDate.now before 11-00)
# curl -X DELETE http://localhost:8080/mvs/rest/user/votes
DELETE http://localhost:8080/mvs/rest/user/votes

###
###check
# curl http://localhost:8080/mvs/rest/user/votes
GET http://localhost:8080/mvs/rest/user/votes

<> 2020-05-29T124804.200.json

###C:\Users\barse\AppData\Roaming\JetBrains\IntelliJIdea2020.1\scratches\scratch.http
###TooBox URL
###jetbrains://idea/navigate/reference?project=MenuVotingSystem&path=scratch.http