
#############################RESTOURANT#################################################################################

###AdminRestaurantRestController---------------------------------------------------------------------------------------
###createWithLocation--------------------------------------------------------------------------------------------------
# curl -X POST -d '{"name":"Mama_Roma","address":"пр.Стачек","phone":"318-56-98","url":"mamaroma.ru"}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/restaurants --user admin@gmail.com:admin
POST http://localhost:8080/mvs/rest/admin/restaurants
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "Mama_Roma",
  "address": "пр.Стачек",
  "phone": "318-56-98",
  "url": "mamaroma.ru"
}

###createWithLocation Validation Error---------------------------------------------------------------------------------
# curl -X POST -d '{"name":"M","address":"пр","phone":"318","url":"m"}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/restaurants --user admin@gmail.com:admin
POST http://localhost:8080/mvs/rest/admin/restaurants
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "M",
  "address": "пр",
  "phone": "318",
  "url": "m"
}

###update restaurant id=100015 (if exist)------------------------------------------------------------------------------
# curl -X PUT -d '{"name":"Update_Roma","address":"пр.СтачекUpdate","phone":"(812)318-56-98","url":"update.ru"}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/restaurants/100015 --user admin@gmail.com:admin
PUT http://localhost:8080/mvs/rest/admin/restaurants/100015
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "Update_Roma",
  "address": "пр.СтачекUpdate",
  "phone": "(812)318-56-98",
  "url": "update.ru"
}

###update restaurant NotFound (422 - Unprocessable Entity) id=1--------------------------------------------------------
# curl -X PUT -d '{"name":"Up_Roma","address":"пр.СтачекUp","phone":"(812)318-56-98","url":"up.ru"}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/restaurants/1 --user admin@gmail.com:admin
PUT http://localhost:8080/mvs/rest/admin/restaurants/1
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "Up_Roma",
  "address": "пр.СтачекUp",
  "phone": "(812)318-56-98",
  "url": "up.ru"
}

### DELETE restaurant id=100015 (if exist)-----------------------------------------------------------------------------
# curl -X DELETE http://localhost:8080/mvs/rest/admin/restaurants/100015 --user admin@gmail.com:admin
DELETE http://localhost:8080/mvs/rest/admin/restaurants/100015
Authorization: Basic admin@gmail.com admin

### DELETE restaurant NotFound (422 - Unprocessable Entity) id=1-------------------------------------------------------
# curl -X DELETE http://localhost:8080/mvs/rest/admin/restaurants/1 --user admin@gmail.com:admin
DELETE http://localhost:8080/mvs/rest/admin/restaurants/1
Authorization: Basic admin@gmail.com admin

###getAllWithTodayMenu ---------------------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/admin/restaurants/dishes --user admin@gmail.com:admin
GET http://localhost:8080/mvs/rest/admin/restaurants/dishes
Authorization: Basic admin@gmail.com admin

###

###UserRestaurantRestController----------------------------------------------------------------------------------------
###get-----------------------------------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants/100003 --user user@yandex.ru:password
GET http://localhost:8080/mvs/rest/user/restaurants/100003
Authorization: Basic user@yandex.ru password

###get(check for ROLE_ADMIN)-------------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants/100003 --user admin@gmail.com:admin
GET http://localhost:8080/mvs/rest/user/restaurants/100003
Authorization: Basic admin@gmail.com admin

###get restaurant NotFound (UNPROCESSABLE_ENTITY) id=1-----------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants/1 --user user@yandex.ru:password
GET http://localhost:8080/mvs/rest/user/restaurants/1
Authorization: Basic user@yandex.ru password

###getAll(ROLE_USER)---------------------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants --user user@yandex.ru:password
GET http://localhost:8080/mvs/rest/user/restaurants
Authorization: Basic user@yandex.ru password

###getAll(ROLE_ADMIN)--------------------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants  --user admin@gmail.com:admin
GET http://localhost:8080/mvs/rest/user/restaurants
Authorization: Basic admin@gmail.com admin

###getAll(ROLE_ROLE_ANONYMOUS)-----------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants
GET http://localhost:8080/mvs/rest/user/restaurants

###getByName-----------------------------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants/byName?name=McDonalds --user user@yandex.ru:password
GET http://localhost:8080/mvs/rest/user/restaurants/byName?name=McDonalds
Authorization: Basic user@yandex.ru password

###getByName restaurant NotFound (422 - Unprocessable Entity") name=unknownName----------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants/byName?name=unknownName --user user@yandex.ru:password
GET http://localhost:8080/mvs/rest/user/restaurants/byName?name=unknownName
Authorization: Basic user@yandex.ru password

###getAllWithTodayMenu (ROLE_USER) ------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants/dishes//today --user user@yandex.ru:password
GET http://localhost:8080/mvs/rest/user/restaurants/dishes/today
Authorization: Basic user@yandex.ru password

###getAllWithTodayMenu (ROLE_ADMIN) ------------------------------------------------------------------------------------
# curl http://localhost:8080/mvs/rest/user/restaurants/dishes/today --user admin@gmail.com:admin
GET http://localhost:8080/mvs/rest/user/restaurants/dishes/today
Authorization: Basic admin@gmail.com admin

###




###
