
################################USER####################################################################################

###AdminUserRestController

###getAll
# curl http://localhost:8080/mvs/rest/admin/users
GET http://localhost:8080/mvs/rest/admin/users

<> 2020-05-28T075757.200.json

### GET user id=100000
# curl http://localhost:8080/mvs/rest/admin/users/100000
GET http://localhost:8080/mvs/rest/admin/users/100000

<> 2020-05-28T081451.200.json

###

### Create user
# curl -X POST -d '{"name":"NewName","email":"new@nuevo.ru","password":"passwordNew","roles":["ROLE_USER"]}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/users
POST http://localhost:8080/mvs/rest/admin/users
Content-Type: application/json

{
  "name": "NewName",
  "email": "new@nuevo.ru",
  "password": "passwordNew",
  "roles": [
    "ROLE_USER"
  ]
}

<> 2020-05-28T082130.201.json

###update user 100016
# curl -X PUT -d '{"name":"NameUpdate","email":"nghhgjhh@gmail.com","password":"passwordUpdate","roles":["ROLE_USER"]}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/users/100016
PUT http://localhost:8080/mvs/rest/admin/users/100016
Content-Type: application/json

{
  "name": "NameUpdate",
  "email": "nghhgjhh@gmail.com",
  "password": "passwordUpdate",
  "roles": [
    "ROLE_USER"
  ]
}
###

### DELETE user id=100016

# curl -X DELETE http://localhost:8080/mvs/rest/admin/users/100016
DELETE http://localhost:8080/mvs/rest/admin/users/100016

###getByMail
# curl http://localhost:8080/mvs/rest/admin/users/by?email=user@yandex.ru
GET http://localhost:8080/mvs/rest/admin/users/by?email=user@yandex.ru

###enable
# curl -X PATCH -H "Content-Type:application/json" http://localhost:8080/mvs/rest/admin/users/100000?enabled=false
PATCH http://localhost:8080/mvs/rest/admin/users/100000?enabled=false
Content-Type: application/json

###ProfileUserRestController(id = 100000)
###get
# curl http://localhost:8080/mvs/rest/profile
GET http://localhost:8080/mvs/rest/profile

### update user profile
# curl -X PUT -d '{"name":"NameUpdate","email":"update@a","password":"passwordUpdate","roles":["ROLE_USER"]}' -H "Content-Type:application/json" http://localhost:8080/mvs/rest/profile
PUT http://localhost:8080/mvs/rest/profile
Content-Type: application/json

{
  "name": "NameUpdate",
  "email": "update@a",
  "password": "passwordUpdate",
  "roles": ["ROLE_USER"]
}


### delete user profile
# curl -X DELETE http://localhost:8080/mvs/rest/profile
DELETE http://localhost:8080/mvs/rest/profile

### check delete
# curl http://localhost:8080/mvs/rest/admin/users
GET http://localhost:8080/mvs/rest/admin/users

###C:\Users\barse\AppData\Roaming\JetBrains\IntelliJIdea2020.1\scratches\scratch.http
###TooBox URL
###jetbrains://idea/navigate/reference?project=MenuVotingSystem&path=scratch.http